package Test;

import Driver.Driver;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.testng.annotations.Test;



public class TestAutomation2213  extends Driver  {

    @Test
    public void BonprixShopTester() throws InterruptedException {
       getDriver().get("https://www.bonprix.ro/");
        waitFewSecs();
        WebElement refuzConsimtamant=getDriver().findElement(By.id("JOISH987_inlineRejectBar_btn"));
        refuzConsimtamant.click();
        waitFewSecs();
        WebElement sale=getDriver().findElement(By.cssSelector("div>[href='/categorie/3794/sale/']"));
        sale.click();
        waitFewSecs();
        WebElement barbatiStanga=getDriver().findElement(By.cssSelector("#category-list > li > ul > li:nth-child(2) > a"));
        barbatiStanga.click();
        waitFewSecs();
        WebElement closeAdvertisment=getDriver().findElement(By.cssSelector("[class='button-icon modal-new-header__close button-icon modal-new-header__close--withBG']"));
        closeAdvertisment.click();
        waitFewSecs();
        WebElement imbracaminte=getDriver().findElement(By.cssSelector("#category-list > li > ul > li:nth-child(3) > a"));
        scrollTo(imbracaminte);
        waitFewSecs();
        imbracaminte.click();
        waitFewSecs();
        WebElement marimeL=getDriver().findElement(By.cssSelector("[href='/categorie/1020/imbracaminte/marimi_L/']"));
        scrollTo(marimeL);
        waitFewSecs();
        marimeL.click();
        waitFewSecs();
        WebElement culoareRosu=getDriver().findElement(By.cssSelector("[href='/categorie/1020/imbracaminte/marimi_L-culori_rosu/']"));
        scrollTo(culoareRosu);
        waitFewSecs();
        culoareRosu.click();
        waitFewSecs();
        WebElement produs1=getDriver().findElement(By.cssSelector("[id='48088-go']"));
        produs1.click();
        waitFewSecs();
        WebElement adaugaProdus1Cos=getDriver().findElement(By.cssSelector("[class='btn btn-success btn-buy']"));
        scrollTo(adaugaProdus1Cos);
        adaugaProdus1Cos.click();
        waitFewSecs();
        WebElement inapoiLaCump1=getDriver().findElement(By.cssSelector("[href='/intoarcere-la-cumparaturi']"));
        scrollTo(inapoiLaCump1);
        waitFewSecs();
        inapoiLaCump1.click();
        waitFewSecs();
        WebElement haineBarbati=getDriver().findElement(By.cssSelector("[href='/categorie/2/barbati/']"));
        scrollTo(haineBarbati);
        haineBarbati.click();
        waitFewSecs();
        WebElement bestSellers=getDriver().findElement(By.cssSelector(".list-group-item li>[href='/categorie/631/moda-pentru-barbati-bestseller-uri/']"));
        scrollTo(bestSellers);
        waitFewSecs();
        bestSellers.click();
        waitFewSecs();
        WebElement marimeLBestSellers=getDriver().findElement(By.cssSelector("[href='/categorie/631/moda-pentru-barbati-bestseller-uri/marimi_L/']"));
        scrollTo(marimeLBestSellers);
        waitFewSecs();
        marimeLBestSellers.click();
        waitFewSecs();
        WebElement culoare=getDriver().findElement(By.xpath("//*[@id='filterList']/li[2]/ul/li[7]/a"));
        scrollTo(culoare);
        waitFewSecs();
        culoare.click();
        waitFewSecs();
        WebElement produs2=getDriver().findElement(By.id("46427-go"));
        scrollTo(produs2);
        waitFewSecs();
        produs2.click();
        waitFewSecs();
        WebElement sizeL=getDriver().findElement(By.xpath("//*[@id='product-form']/form/div[2]/div/label[3]"));
        scrollTo(sizeL);
        sizeL.click();
        waitFewSecs();
        WebElement adaugaInCosProd2=getDriver().findElement(By.cssSelector("[class='btn btn-success btn-buy']"));
        adaugaInCosProd2.click();
        waitFewSecs();
        WebElement inapoiLaCump2=getDriver().findElement(By.cssSelector("[href='/intoarcere-la-cumparaturi']"));
        inapoiLaCump2.click();
        waitFewSecs();
        WebElement searchbar=getDriver().findElement(By.name("search"));
        scrollTo(searchbar);
        String slipBarbati="camasa";
        searchbar.sendKeys(slipBarbati);
        waitFewSecs();
        searchbar.sendKeys(Keys.ENTER);
        waitFewSecs();
        WebElement camasiBarbati=getDriver().findElement(By.cssSelector("[href='/cauta/camasa/categorie_2']"));
        camasiBarbati.click();
        waitFewSecs();
        WebElement marimeCamasaL=getDriver().findElement(By.cssSelector("[href='/cauta/camasa/marimi_L-categorie_2']"));
        scrollTo(marimeCamasaL);
        waitFewSecs();
        marimeCamasaL.click();
        waitFewSecs();
        WebElement camasaManecaLunga=getDriver().findElement(By.cssSelector("[href='/cauta/camasa/marimi_L-lungimea~manecii_cu~maneca~lunga-categorie_2']"));
        scrollTo(camasaManecaLunga);
        waitFewSecs();
        camasaManecaLunga.click();
        waitFewSecs();
        WebElement camasaAlba=getDriver().findElement(By.xpath("//*[@id='filterList']/li[3]/ul/li[1]/a"));
        scrollTo(camasaAlba);
        waitFewSecs();
        camasaAlba.click();
        waitFewSecs();
        WebElement prod3=getDriver().findElement(By.id("118642-go"));
        scrollTo(prod3);
        waitFewSecs();
        waitFewSecs();
        prod3.click();
        waitFewSecs();
        WebElement adaugareInCosProd3=getDriver().findElement(By.cssSelector("[class='btn btn-success btn-buy']"));
        scrollTo(adaugareInCosProd3);
        waitFewSecs();
        adaugareInCosProd3.click();
        WebElement inapoiLaCump3=getDriver().findElement(By.cssSelector("[href='/intoarcere-la-cumparaturi']"));
        waitFewSecs();
        inapoiLaCump3.click();
        waitFewSecs();
        WebElement  cos=getDriver().findElement(By.xpath("/html/body/header/div[2]/div/div[4]/div/div[1]/div/div/div[2]/a[3]"));
        scrollTo(cos);
        waitFewSecs();
        cos.click();
        waitFewSecs();
        WebElement search=getDriver().findElement(By.name("searchText"));
        search.sendKeys("pantaloni");
        search.sendKeys(Keys.ENTER);
        waitFewSecs();
        WebElement barbatiPants=getDriver().findElement(By.cssSelector("[href='/cauta/pantaloni/categorie_2']"));
        barbatiPants.click();
        waitFewSecs();
        WebElement marimeLPantaloni=getDriver().findElement(By.cssSelector("[href='/cauta/pantaloni/marimi_L-categorie_2']"));
        scrollTo(marimeLPantaloni);
        marimeLPantaloni.click();
        waitFewSecs();

        WebElement pantalon1=getDriver().findElement(By.xpath("//*[@id='31265-go']"));
        scrollTo(pantalon1);
        waitFewSecs();
        waitFewSecs();
        pantalon1.click();
        WebElement buyPantalon=getDriver().findElement(By.cssSelector("[class='btn btn-success btn-buy']"));
        buyPantalon.click();
        waitFewSecs();
        WebElement veziCosul=getDriver().findElement(By.xpath("//*[@id='before-purchase']/div/div/div[1]/div[1]/div[2]/div/div[3]/a"));
       scrollTo(veziCosul);
       waitFewSecs();
        veziCosul.click();
        waitFewSecs();
        WebElement costLivrare=getDriver().findElement(By.cssSelector("[class='btn btn--link btn--link-normalized basket-summary__delivery-costs-trigger']"));
        scrollTo(costLivrare);
        costLivrare.click();
        waitFewSecs();
        WebElement closeFrameCosts=getDriver().findElement(By.cssSelector("[class='button-icon modal-header__close']"));
        closeFrameCosts.click();
        waitFewSecs();
        WebElement comanda=getDriver().findElement(By.xpath("//*[@id='app']/div[3]/div/div[3]/div[1]/div[2]/div/div[1]/div[3]/div[2]/form/button"));
        scrollTo(comanda);
        comanda.click();
        waitFewSecs();
        WebElement comandaEmail=getDriver().findElement(By.name("email"));
        scrollTo(comandaEmail);
        comandaEmail.sendKeys("exampleEmail24@yahoo.com");
        waitFewSecs();
        WebElement goAhead=getDriver().findElement(By.xpath("//*[@id='app']/div[2]/div/div[2]/div/div[1]/div[2]/div[3]/div/form/button"));
        scrollTo(goAhead);
        waitFewSecs();
        goAhead.click();
        waitFewSecs();
        WebElement emailRepeat=getDriver().findElement(By.cssSelector(".form-input>[class='form-input__wrapper']>input[name='emailRepeat']"));
        scrollTo(emailRepeat);
        emailRepeat.click();
        emailRepeat.sendKeys("exampleEmail24@yahoo.com");
        WebElement firstName=getDriver().findElement(By.name("firstName"));
        firstName.sendKeys("Laszlo Istvan ");
        waitFewSecs();
        WebElement lastName=getDriver().findElement(By.name("lastName"));
        lastName.sendKeys("Kovacs");
        waitFewSecs();
        WebElement phoneNumber=getDriver().findElement(By.name("mobilePhone"));
        scrollTo(phoneNumber);
        phoneNumber.sendKeys("0765878529");
        waitFewSecs();
        WebElement birthDate=getDriver().findElement(By.cssSelector("[class='form-input__input form-input__input--valid form-input__input--has-not-value']"));
        birthDate.click();
        waitFewSecs();
        birthDate.sendKeys("21 Jul 1997");
        waitFewSecs();
        WebElement street=getDriver().findElement(By.cssSelector("input[name='street']"));
        scrollTo(street);
        street.sendKeys("Str. Caprioarei ");
        waitFewSecs();
         WebElement streetAddress=getDriver().findElement(By.cssSelector("input[name='streetNumber']"));
         streetAddress.sendKeys("48/C");
         WebElement postCode=getDriver().findElement(By.cssSelector("input[name='postCode']"));
         postCode.sendKeys("549781");
         waitFewSecs();
         WebElement cityName=getDriver().findElement(By.cssSelector("input[name='city']"));
         scrollTo(cityName);
         cityName.sendKeys("Ghindari");
         waitFewSecs();
         WebElement faraCont=getDriver().findElement(By.xpath("//*[@id='app']/div[2]/div/div[2]/div/div[1]/div[2]/div[3]/div/div/form/div[12]/div/label"));
         faraCont.click();
         waitFewSecs();
         WebElement continueFaraCont=getDriver().findElement(By.cssSelector("[class='btn btn--stretch btn-primary btn-size--default']"));
         continueFaraCont.click();
         waitFewSecs();
         WebElement rambursPay=getDriver().findElement(By.xpath("//*[@id='app']/div[2]/div/div[2]/div/div[1]/div[2]/div[3]/div[1]/form/div[4]/div/div/div/span/div[2]/label/div[1]"));
         scrollTo(rambursPay);
         rambursPay.click();
         waitFewSecs();
         WebElement consimtamant=getDriver().findElement(By.xpath("//*[@id='app']/div[2]/div/div[2]/div/div[1]/div[2]/div[3]/div[4]/form/div[1]/label"));
         consimtamant.click();
         waitFewSecs();
         WebElement top=getDriver().findElement(By.xpath("//*[@id='app']/header/div[3]/div/div"));
         scrollTo(top);
         waitFewSecs();

          getDriver().get("https://www.shutterstock.com/image-vector/thank-you-watching-retro-typography-600w-1200878692.jpg");
          waitFewSecs();
          waitFewSecs();
          waitFewSecs();
    }


}
